//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudenetForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentInfo
    {
        public int studentId { get; set; }
        public Nullable<int> YearId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string S_Adress { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Place_Of_Birth { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> class_YearsId { get; set; }
        public string Guardian { get; set; }
        public string Relation { get; set; }
        public string G_Address { get; set; }
        public string Contact { get; set; }
    
        public virtual ClassYear ClassYear { get; set; }
        public virtual SchoolYear SchoolYear { get; set; }
        public virtual StatusOfStudent StatusOfStudent { get; set; }
    }
}
